title: "Steven Tsai"
logo: "/images/photo.png?raw=true"
description: >
  I'm Steven, NPI Professional Engineering Project Manager 
  <br><br>
  I'm passionate about project management, data analysis, technology innovation.
  <br><br>
  <a href="https://www.linkedin.com/in/hsuanyutsai/">View My LinkedIn Profile</a>
  <br><br>

theme: jekyll-theme-minimal

show_downloads: false
google_analytics: ""  # Add your GA tracking ID if needed, e.g., "UA-XXXXXXXXX-X"
author:
  name: "Steven Tsai"
  email: "steven.hy.tsai@icloud.com"

# Build settings
markdown: kramdown
